### ISSUE TITLE
How to connect to the robot

### ISSUE THREAD

**Issue by michtesar** [minoskt/ComedyParser#1]
Hi, I am new to the RoboThespian. I am trying to get your code work on my robot. I just put the robot into a switch and trying to connect to it while running ```python playComedy.py input.json`. I guess I don't have a correct IP address. When I enter an IP as a second parameter in format ```https://rt-XXXX.robothespian.co.uk/``` it does not work. It said IP address is already in use. Can you please help me? Thank you for your time, Michael

**Comment by minoskt** [comment]
Hi

Thanks for your interest on this project.

It’s been a lot time since I worked on this (was past of my internship at Engineered Arts) and unfortunately I don’t have access to the robot any more. Moreover, I am sure the robot’s API has changed a lot since then. I suggest you first communicate with Engineered Arts and ask them to send you details on how to communicate / control the robot using sockets. Then do the required changes to `Communication.py`.

May I asked what’s your general aim? Very happy to help you if I can (I also have several ideas of how this could be improved using AI). Feel free to email me at k.katevas at imperial.ac.uk.

Thanks
Minos

**Comment by michtesar** [comment]
Minos, thank your for a reply I would like to be able to do followings: TTS, cartesian move with hands and head, transfer audio from microphones and also camera. But there is no mentions in the documentation. What a shame :/
